### ISSUE TITLE
website broken, AppImages broken

### ISSUE THREAD

**Issue by romain-dartigues** [geeqie/geeqie.github.io#1]
The group comment at https://github.com/geeqie promote http://bestimageviewer.github.io/geeqie (404 not found).

The geeqie.github.io redirect to www.geeqie.org and links to https://*.geeqie.org are invalid (invalid certificate).

All the download links to the AppImage at https://www.geeqie.org/AppImage/ are invalid (404 not found).

## Edit

Found through https://github.com/BestImageViewer/geeqie the functional AppImage page is https://cclark.uk/Geeqie/.

Should [the link](https://github.com/geeqie/geeqie.github.io/blob/8c4e0071fee9a7d88335ef0dcb59fb7f2b216fab/index.html#L268) point to this external page? As it is the case for the FlatPack, Linux distributions, etc.

**Comment by caclark** [comment]
Changes to the websites were made very recently. The site access should now be ok, but you may need to clear the browser cache.
The AppImage page is now correct, but the AppImages themselves are still on my domain - I am not sure how to handle that yet.
