### ISSUE TITLE
Huge homepage size

### ISSUE THREAD

**Issue by ctrlaltca** [geeqie/geeqie.github.io#5]
I don't know if this can be considered a bug, but I noticed that the https://www.geeqie.org/ homepage is quite slow to load.
It seems it totals 47MB in size, including a 33 MB image at https://static.pexels.com/photos/60838/pexels-photo-60838.png.

**Comment by lge** [comment]
On Sat, 18 Dec 2021 at 15:50, ctrlaltca ***@***.***> wrote:
>
> I don't know if this can be considered a bug, but I noticed that the
https://www.geeqie.org/ homepage is quite slow to load.
> It seems it totals 47MB in size, including a 33 MB image at
https://static.pexels.com/photos/60838/pexels-photo-60838.png.

Yes, on a 10 MBit/s line, the page takes 40 to 50 seconds to load (cache
cold).
That would be these two, from https://www.geeqie.org/web-files/new-age.css:

section.cta {
  background-image: url('
https://images.pexels.com/photos/230324/pexels-photo-230324.jpeg');
section.hta {
  background-image: url('
https://static.pexels.com/photos/60838/pexels-photo-60838.png');

> 12 MB, the laptop, pexels-photo-230324.jpeg JPEG 5977x3609 5977x3609+0+0
8-bit sRGB 12.19MiB
> 35 MB, the camera, pexels-photo-60838.png PNG 3554x2360 3554x2360+0+0
16-bit sRGB 34.0745MiB

Can probably be changed to "dynamic loading", and also be "web optimized"?
Resolution seems excessive for a background image on a web page section.
